### ISSUE TITLE
Crash on Launch: ladysnake.satin.api.managed.ManagedShaderEffect.getShaderEffect() is null

### ISSUE THREAD

**Issue by HenryXiaoYang** [Ladysnake/Satin#47]
**Describe the bug**
Crash when launching game.

Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_279.method_1264(String)" because the return value of "ladysnake.satin.api.managed.ManagedShaderEffect.getShaderEffect()" is null
	at me.nullpoint.api.managers.ShaderManager.applyFlow(ShaderManager.java:64) ~[nullpoint-v2.1.3(2).jar:?]
	at net.minecraft.class_442.method_25394(class_442.java:1074) ~[client-intermediary.jar:?]
	at net.minecraft.class_425.method_25394(class_425.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:920) ~[client-intermediary.jar:?]
	... 6 more

**To Reproduce**
Run on ARM macos, m1 chip. Minecraft version 1.20.4, java21. Crashed on both arm java and x86 java.

**Environment:**
 - Minecraft Version 1.20.4
 - Satin Version 1.16.0
 - Inside or Outside of a development environment ? Outside

**Screenshots (optional)**
*If applicable, add screenshots to help explain your problem.*

**Additional context (optional)**
*Add any other context about the problem here.*

You can remove any unused optional section.

**Comment by HenryXiaoYang** [comment]
Tested with Satin 2.0.0, still crashes
```
20:39:11] [Render thread/WARN]: Error loading class: net/minecraft/class_9779 (java.lang.ClassNotFoundException: net/minecraft/class_9779)
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 2024-07-30 20:39:12
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'satin'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:487)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_761 failed
	at org.ladysnake.satin.api.event.WorldRendererReloadCallback.lambda$static$1(WorldRendererReloadCallback.java:30)
	at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:54)
	at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:50)
	at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:47)
	at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:44)
	at org.ladysnake.satin.api.event.WorldRendererReloadCallback.<clinit>(WorldRendererReloadCallback.java:29)
	at org.ladysnake.satin.Satin.onInitializeClient(Satin.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_761 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 18 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for mixins.satin.client.json:event.WorldRendererMixin from mod satin during activity: [Transform -> Method firePreRenderEntities(Lnet/minecraft/class_9779;ZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lorg/joml/Matrix4f;Lorg/joml/Matrix4f;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> INVOKEINTERFACE -> net/minecraft/class_9779::method_60637:(Z)F]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 21 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.class_9779
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:786)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:772)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:738)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307)
	... 27 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_9779
	... 31 more
```

**Comment by HenryXiaoYang** [comment]
Crashes without Satin, maybe it is not Satin's fault for crashing...
